### ISSUE TITLE
Errors installing on Debian 8

### ISSUE THREAD

**Issue by isleofmax** [perl6/perl6-lwp-simple#11]
I have a Debian 8: Linux maxp-deb 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
All the tests passed but when install I have these errors:
==> Installing LWP::Simple
LWP::Simple:ver<0.090>:auth<Cosimo Streppone>:api<> already installed
  in block  at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 61
  in sub indir at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method install at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 42
  in method install at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 190
  in method resolve at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 263
  in sub MAIN at /home/massimo/rakudo-star-2016.11/install/bin/panda line 20
  in block <unit> at /home/massimo/rakudo-star-2016.11/install/bin/panda line 165

Actually thrown at:
  in block  at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 61
  in sub indir at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method install at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/85367160D11E565B2D089507C79BC309215430D6 (Panda::Installer) line 42
  in method install at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 190
  in method resolve at /home/massimo/rakudo-star-2016.11/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 263
  in sub MAIN at /home/massimo/rakudo-star-2016.11/install/bin/panda line 20
  in block <unit> at /home/massimo/rakudo-star-2016.11/install/bin/panda line 165

**Comment by zoffixznet** [comment]
The error message says `LWP::Simple:ver<0.090>:auth:api<>`  **`already installed`**

So there's no problem with the module.

More recent Rakudo Star comes with [`zef` module manager](https://modules.perl6.org/repo/zef) that shows better message.
