### ISSUE TITLE
version mismatch between META6.json and module source

### ISSUE THREAD

**Issue by zakame** [perl6/perl6-lwp-simple#18]
Just following up from the observation in https://github.com/perl6/perl6-lwp-simple/issues/17#issuecomment-318019368

>running with --debug shows that zef actually does get 0.092, but because of https://github.com/perl6/perl6-lwp-simple/blob/master/lib/LWP/Simple.pm#L9 it thinks we're installing 0.090

Checking META6.json, it does have version `0.092`.  Is there a rubric regarding this? such as removing the `:ver<>` qualifier in the source and let META6.json be the source of truth?

**Comment by zakame** [comment]
Thanks @zoffixznet!

**Comment by zoffixznet** [comment]
Fixed thanks. Normally, yeah, I'd just keep the version in META6.json, but I see this module is also using it in the UA string, so I just bumped it in the source.
