### ISSUE TITLE
rakudo.org is used for non-HTTPS tests, but will be forced to HTTPS very soon

### ISSUE THREAD

**Issue by zoffixznet** [perl6/perl6-lwp-simple#25]
Was added to https://github.com/perl6/perl6-lwp-simple/commit/0e0663ada2b435ef281706e9e842463c92b6909e

But we're currently right in the middle of upgrading rakudo.org and it'll be forced to use HTTPS in a week or two.

Comments from the commit:

```
 zoffixznet replied 24 minutes ago

Please don't use rakudo.org for plain HTTP. It will be forced to HTTPS in just a week or a couple.

Does http://httpbin.org/ work?
@stmuk
Member
stmuk replied 20 minutes ago

maybe http://neverssl.com/?
```

**Comment by dwarring** [comment]
Or just do away with the non https test. Plain http websites are a dying breed.

**Comment by zoffixznet** [comment]
Feels weird to never test anything but optional functionality of a popular module included in a core dist. Especially since there are plenty ofnon-HTTPS of uses for this module other than browsing websites and it's trivial to perform that test.

**Comment by dwarring** [comment]
There's other use of http in the test suite. [w3-latin1-utf8.t](https://github.com/perl6/perl6-lwp-simple/blob/f4aa49c156a640b1079f8b009065e1c5f8134cc2/t/get-w3-latin1-utf8.t) fetches from http://www.w3.org/2006/11/mwbp-tests/test-encoding-3.html and [get-w3-redirect.t](https://github.com/perl6/perl6-lwp-simple/blob/f4aa49c156a640b1079f8b009065e1c5f8134cc2/t/get-w3-redirect.t) seems rely on a plain http redirect from http://jigsaw.w3.org.

Short answer could be to also use http://www.w3.org/ and raise another ticket regarding the overall reliance on http://www.w3.org/ remaining http without a redirect.

**Comment by dwarring** [comment]
FWIW the Perl  5 LWP module uses [http://www.example.com](https://github.com/libwww-perl/libwww-perl/blob/master/t/base/default_content_type.t which is referenced as a reserved site in [RFC2606](https://tools.ietf.org/html/rfc2606)
