### ISSUE TITLE
Tests rely on w3c.org and jigsaw.org not redirecting to https

### ISSUE THREAD

**Issue by dwarring** [perl6/perl6-lwp-simple#26]
Just to point out that there are tests in t/getstore.t t/get-w3-latin1-utf8.t that will fail if http://w3c.org ever start redirecting to https: and the optional IO::Socket::SSL module is not installed.

Likewise, get-w3-redirect.t relies on a non https redirection from http://jigsaw.w3.org/HTTP/300/301.html.

Is this safe? Is there a better solution?

**Comment by JJ** [comment]
Yep, that happens pretty much everywhere... I don't think there's a better solution, unless you suggest one.

**Comment by Scimon** [comment]
I could look at updating them to use my test http server.

**Comment by JJ** [comment]
@Scimon that might be a good and maybe permanent solution :-)
