### ISSUE TITLE
"Expected MAST::Frame, but didn't get one" error

### ISSUE THREAD

**Issue by bbkr** [perl6/perl6-lwp-simple#3]
File Zonk.pm
```
use LWP::Simple;
```

Error occurs when module is loaded:
```
$ perl6 -I. -e 'use Zonk;'
===SORRY!===
Expected MAST::Frame, but didn't get one
```

Rakudo 2016.06 MoarVM
IO::Socket::SSL installed
OS X 10.10.5

In command line `use LWP::Simple;` works without issues.

**Comment by bbkr** [comment]
Update: if SSL is explicitly loaded then everything works:

Zonk.pm
```
use IO::Socket::SSL;
use LWP::Simple;
```

So it looks like "try require" is breaking something in this module.

**Comment by gfldex** [comment]
Problem goes away if IO::Socket::SSL is not installed.

**Comment by jonathanstowe** [comment]
See https://github.com/gfldex/perl6-pod-to-bigpage/issues/1

**Comment by jonathanstowe** [comment]
I've moved the  requiring of the IO::Socket::SSL nto the request_shell method and that seems to work fine, I think the problem is that something is getting compiled in where it shouldn't.
