### ISSUE TITLE
Deprecate this module

### ISSUE THREAD

**Issue by JJ** [perl6/perl6-lwp-simple#32]
Last [Rakudo star release says](https://rakudo.org/post/announce-rakudo-star-release-2018-10)

> LWP::Simple is deprecated and will be removed. Please use "HTTP::UserAgent".

Should we just put that in the README.md and help other modules transition to HTTP::UserAgent?

**Comment by Scimon** [comment]
I think there is a place for LWP::Simple though. Possibly rewriting it to be based on HTTP::UserAgent but keeping the easier to use syntax?

Sometimes you just want to get a URL...

**Comment by JJ** [comment]
Then it would be great if you redid those tests...

**Comment by Scimon** [comment]
I shall take a look today.
