### ISSUE TITLE
test failures with Failed to resolve host name

### ISSUE THREAD

**Issue by coke** [perl6/perl6-lwp-simple#4]
t/basic-auth.t .................. ok
Failed to resolve host name

The company I work for forces any external http/https connections to go through a proxy - the hosts aren't even exposed to us in internal DNS.

**Comment by zoffixznet** [comment]
Also, to add, `t/get-w3-latin1-utf8.t` seems to be floppy, failing some times.

**Comment by coke** [comment]
#5 has the failing file name and more details, and suggestion, closing this ticket.
