### ISSUE TITLE
t/custom-headers-and-content.t - bad host

### ISSUE THREAD

**Issue by coke** [perl6/perl6-lwp-simple#5]
The url used to verify that connections work in this file is:

my $host    = 'http://froggs.de/cgi-bin/test/test.cgi';

But this host doesn't have any particular uptime guarantees, nor is it likely to be accessible through a corporate firewall.

We should change it to something in the perl6.org domain - preferably a static file that can be quickly/easily served, and can be more reliably whitelisted

**Comment by szabgab** [comment]
http://httpbin.org/ might be a good site to use for testing.

**Comment by JJ** [comment]
@szabgab not any more...

**Comment by JJ** [comment]
@coke can we maybe put some very basic REST server to do that now?
